### ISSUE TITLE
Unable to find version matching 2.2.0

### ISSUE THREAD

**Issue by brad4d** [jwlawson/actions-setup-bazel#16]
Starting Aug 27, 2021 10:20AM PDT our project which uses this action started failing with the error

```
 with:
    bazel-version: 2.2.0
    github-api-token: ***
  env:
    VERSION_NODEJS: 10.21.0
    UNSYMLINK_DIR: bazel-bin-unsymlink
    JAVA_HOME_11.0.12_x64: /opt/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME_11_0_12_X64: /opt/hostedtoolcache/jdk/11.0.12/x64
Error: Unable to find version matching 2.2.0
```

Our action config file is here

https://github.com/google/closure-compiler/blob/master/.github/workflows/ci.yaml

I briefly tried changing our config to use `2.x` then not specifying a version at all.

Both failed to find a bazel version to use.
Maybe this is a problem with where bazel is being grabbed from, but I'm not sure how best to find out.

**Comment by jwlawson** [comment]
Thanks for letting me know. It might be something to do with pagination of the releases but I'd still expect leaving the version blank would work. Either way I'll take a look.

**Comment by brad4d** [comment]
I've switched our project to use https://github.com/bazelbuild/setup-bazelisk instead.
It's actually a better fit, because it makes the action more consistent with our manual build instructions.

@jwlawson As far as I'm concerned this issue can be closed, but I'll leave it open because there may actually be something wrong you want to investigate here. Thanks for looking into it.
