### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by grencez** [jwlawson/actions-setup-bazel#22]
I'm seeing this warning: Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: jwlawson/actions-setup-bazel@v1

Not urgent. Looks like this is just a warning until mid-2023.

**Comment by jwlawson** [comment]
Thanks for bringing this up! It should now be resolved as of version 1.9.0.
